remote_theme: vectorvcinco/huertito-theme

title: "Huertito: Jardinería Creativa"
author: GitHub User
description: > # this means to ignore newlines until "baseurl:"
  Huertito es un Kit de Jardinería Creativa y un Asistente Digital.
  Copyright 2018® – vectorVcinco

love: Made with love and tamalitos from Mexico

email: huertito@vectorvcinco.design
twitter_username: huertito
github_username:  vectorvcinco

# Build settings
markdown: kramdown

kickstarter: true

exclude:
  - Gemfile
  - Gemfile.lock

footer_sections:
  faq: true
  mediakit: true
  respect: true


collections:
  - features
#  - otherfeatures
  - kitcontents
#  - pricing

environment: production
google_analytics: UA-91857415-2          # Required - replace with your tracking id
